### ISSUE TITLE
IAM roles

### ISSUE THREAD

**Issue by mym** [deliciousbrains/wp-amazon-web-services#41]
Hello,

AWS IAM roles (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) allow for much better security by not having to store credentials on the instance.
When an instance is assigned a role, 'key' and 'secret' arguments are not required anymore when instantiating a new client.

Could you please add support for this?
Cheers

**Comment by A5hleyRich** [comment]
This has been implemented and will be available in the next release.

**Comment by bgrantrobus** [comment]
The last comment indicates this functionality will be "available in the next release", but I don't see any related development in the repo.  I'm wondering if there is a complete implementation forthcoming and if so, when?

If not, I've [worked up a solution](https://github.com/bgrantrobus/wp-amazon-web-services/tree/feature-enhanced-credentials-support) to meet my immediate needs that I would be happy to submit via Pull Request.

**Comment by polevaultweb** [comment]
@bgrantrobus since the start of our development of the [pro version](https://deliciousbrains.com/sneak-peek-amazon-s3-cloudfront-pro/) of Amazon S3 and CloudFront, we have moved all development for these plugins to a private repo, hence the lack of commit activity!

**Comment by polevaultweb** [comment]
You can now use the constant 'AWS_USE_EC2_IAM_ROLE' - https://deliciousbrains.com/wp-offload-s3/doc/iam-roles/
