### ISSUE TITLE
Incorrect plugin activation failure message when curl library for PHP not installed/enabled.

### ISSUE THREAD

**Issue by ianmjones** [deliciousbrains/wp-amazon-web-services#47]
> Plugin could not be activated because it triggered a fatal error.
> 
> The official Amazon Web Services SDK requires PHP 5.3.3+ and cURL 7.16.2+ compiled with OpenSSL and zlib. Your server currently has a cURL version less than 7.16.2.

After getting the above message when trying to activate the plugin I upgraded my server (it was well overdue) and that gave me cURL 7.21.0.

After a full reboot I tried to activate again and got the same message.

A little bit of checking showed that I did not have the curl library installed/enabled for PHP.

Once I installed php5-curl and restarted Apache the plugin activated correctly.

**Comment by hebrides** [comment]
in case you are new, to install php-curl:
```
sudo apt-get install php-curl
```
