### ISSUE TITLE
Wrong Status Message Type When Activation Fails Due To Missing cURL Library.

### ISSUE THREAD

**Issue by ianmjones** [deliciousbrains/wp-amazon-web-services#56]
When the PHP cURL library is missing from the server, an appropriate message is given that the plugin could not be activated, however at first glance the type of message makes it feel like it succeeded. See attached screenshot.

![ember library mediator](https://cloud.githubusercontent.com/assets/4710/5638170/afb99eae-9668-11e4-99a4-befcf47074e4.png)

**Comment by polevaultweb** [comment]
@ianmjones just deactivated the plugin on `develop` and spoofed the `! function_exists( 'curl_version' )` condition to trigger and I see this when I try to activate:

![screen shot 2015-01-07 at 10 32 25](https://cloud.githubusercontent.com/assets/1770201/5644175/9980486e-9658-11e4-80ba-679e1f854525.png)

How are you getting to this notice?

**Comment by ianmjones** [comment]
I'm using:
debian 6.x (32bit)
WordPress 3.9.2
Default 2014 theme (no extra admin themes etc)
Only active plugins: WP Migrate DB Pro and its Media Files addon.

Steps to reproduce:
sudo apt-get remove php5-curl
sudo /etc/init.d/apache2 stop
sudo /etc/init.d/apache2 start

Try and activate plugin from Installed Plugins page.

It's entirely possible this is a problem with WP 3.9.2, I can not reproduce on a new WordPress 4.1 install.

I'm going to close this off for the time being, if anyone else comes up with the problem we can re-open.
