### ISSUE TITLE
Addon installed check fails if addon directory name not as expected.

### ISSUE THREAD

**Issue by ianmjones** [deliciousbrains/wp-amazon-web-services#57]
The check for whether an addon is installed (used in addons view) looks for a given directory/file name in the plugins directory, this is brittle as it is possible to install a plugin with a different directory name.

For example the plugin expects "amazon-s3-cloudfront" but it is possible to clone that addon from github with the directory name wp-amazon-s3-cloudfront which means this plugin always assumes the addon is not installed even though it is installed and can be activated.

**Comment by polevaultweb** [comment]
@ianmjones I think this was an acceptable issue discussed [here](https://github.com/deliciousbrains/wp-amazon-web-services/issues/22), as most users will install from wp.org. 

@bradt I assume you don't want to revisit?
