### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-web-services#58]
- [x] Grunt for assets
- [x] Update .pot file
- [x] Bump version in readme.txt, 
- [x] Bump version in php file header
- [x] Bump version in AWS meta global
- [x] Update required version of Amazon Web Services (`$aws_plugin_version_required`) where necessary 
- [x] Update version of supported addons where necessary in AWS meta global
- [x] Update changelog with commits for this version

**Comment by bradt** [comment]
@polevaultweb I've assigned this to you as well.

**Comment by bradt** [comment]
I can't find these commits

**Comment by polevaultweb** [comment]
Doh, pushed
