### ISSUE TITLE
Investigate signature v4 requirements and propose changes

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-web-services#60]
https://wordpress.org/support/topic/supporting-s3-signature-version-4?replies=1

We should first learn what v4 is and what we need to change.

**Comment by polevaultweb** [comment]
> Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, existing AWS regions continue to support the previous protocol, Signature Version 2. Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4

http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by bradt** [comment]
Do the existing AWS regions work with v4?

**Comment by polevaultweb** [comment]
So v4 is backward compatible with all regions, so we should be using across the board. However, region must be specified in the client factory config. 

We currently only do this if someone has `defined( 'AWS_REGION' )` and of course we set the region to be specific to the bucket when doing things with the S3 client in the AS3CF plugin.

I think we should set the region for every client instantiation, using either the defined region or default of 'us-east-1'.

**Comment by polevaultweb** [comment]
When the AS3CF plugin sets the bucket specific region for actions on existing media, the signature will already be set to v4, so should be fine. Just testing now.

**Comment by polevaultweb** [comment]
Interestingly, this must be the first user to be using buckets in the Frankfurt (eu-central-1) region!

**Comment by bradt** [comment]
Does `AWS_REGION` actually impact anything ATM?

**Comment by polevaultweb** [comment]
I assumed it would be used for setting the region of a bucket created using the plugin, however, I have just used `define( 'AWS_REGION', 'eu-central-1' );` and tried to create a bucket and got the error:
"The unspecified location constraint is incompatible for the region specific endpoint this request was sent to."

**Comment by polevaultweb** [comment]
It was only added here https://github.com/deliciousbrains/wp-amazon-web-services/pull/7 so that the non default bucket regions would work for urls etc, which we have since added support for in AS3CF by recording bucket region in the s3 meta object

**Comment by polevaultweb** [comment]
If we get rid of 'AWS_REGION' the only thing we would lose is the ability to specify a region for a bucket to be created in, which is broken anyway at the moment. If we leave it in, we would need to handle s3 client calls for default regions, as the client region won't get set as they are the default region and will fail.

**Comment by polevaultweb** [comment]
> we would need to handle AS3CF s3 client calls for default regions,

In https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/develop/classes/amazon-s3-and-cloudfront.php#L1131 something like:

``` php
function translate_region( $region ) {
	$region = strtolower( $region );

	switch ( $region ) {
		case 'eu' :
			$region = 'eu-west-1';
			break;
	}

	// make sure we set the client region with the default to overwrite the user defined region
       if ( defined('AWS_REGION') && '' != $region ) {
		$region = 'us-east-1';
	}

	return $region;
}
```

**Comment by polevaultweb** [comment]
@bradt `AWS_REGION` constant removed

**Comment by bradt** [comment]
Looks like I was right about the AWS client...

> Another way to instantiate a service client is using the Aws\Common\Aws object (a.k.a the service builder). The Aws object is essentially a service locator, and allows you to specify credentials and configuration settings such that they can be shared across all client instances. Also, every time you fetch a client object from the Aws object, it will be exactly the same instance.

http://docs.aws.amazon.com/aws-sdk-php/guide/latest/quick-start.html#service-builder
