### ISSUE TITLE
Incorrect region

### ISSUE THREAD

**Issue by JackSW** [deliciousbrains/wp-amazon-web-services#63]
After updating to v0.2.1, the plugin is no longer uploading the images to s3, and I see the following error in my logs:

Error uploading [...]/wordpress/wp-content/uploads/2015/01/1-12-2015-6-49-55-PM.png to S3: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

(If I change the hard-coded region value in amazon-web-services/classes/amazon-web-services.php, it fixes the upload error)

WP: v4.1
Amazon Web Services: v0.2.1
Amazon S3 and CloudFront: v0.8

**Comment by polevaultweb** [comment]
@JackSW is your site hosted on EC2?

**Comment by polevaultweb** [comment]
@JackSW we are working on fixes for this and your [Amazon S3 and CloudFront issue](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/218), would you mind testing the se versions of the plugin to see if they fix your issues?

http://cl.ly/3b1W0q2d2A1W
http://cl.ly/3g1Q303M1215

**Comment by polevaultweb** [comment]
Fixed in 0.2.2
