### ISSUE TITLE
blank S3 and CloudFront config page

### ISSUE THREAD

**Issue by kaichi** [deliciousbrains/wp-amazon-web-services#66]
I am getting an HTTP error upon upload and noticed my "S3 and CloudFront" configure page is blank. I have double checked my IAM policies, even creating a new user / key and still receiving the blank config page. I read issue #63 but no solution pertaining to my situation.

I am using Elastic Beanstalk, previously I had no issues with the plugin. I was able to get the plugins working flawlessly without any issue.

**Comment by polevaultweb** [comment]
Hi @kaichi 

Can you replace this line in your wp-config.php file

`define('WP_DEBUG', false);`

with

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

Then hopefully any errors are captured in `/wp-content/debug.log` and you can paste them here.
