### ISSUE TITLE
Packagist is not updated

### ISSUE THREAD

**Issue by phh** [deliciousbrains/wp-amazon-web-services#69]
0.3.3 was released 3 days ago:
https://github.com/deliciousbrains/wp-amazon-web-services/releases/tag/0.3.3

But the now version is not available on packagist:
https://packagist.org/packages/deliciousbrains/wp-amazon-web-services

You could add a github service hook to notify packagist that there is an update available:
https://packagist.org/about#how-to-update-packages

**Comment by A5hleyRich** [comment]
The packagist repo isn't maintained by us so we can't add the GitHook.

Please use http://wpackagist.org/search?q=amazon-web-services&type=any&search=
