### ISSUE TITLE
Blank Offload S3 page, traced back to PHP Fatal Error

### ISSUE THREAD

**Issue by ericnicolaas** [deliciousbrains/wp-amazon-web-services#70]
I've been wrestling with a blank settings page in Offload S3 (wordpress.org version). This is the error I'm getting in the error log: 

`PHP Fatal error:  Interface 'Guzzle\Common\Exception\GuzzleException' not found in /path/to/wp/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Common/Exception/RuntimeException.php on line 5`

Which is weird, because that interface should be available through the autoloader (it's in the mapping).  

Sounds an awful lot like the problem mentioned in #68.

**Comment by ericnicolaas** [comment]
This error turns up quite a bit on Google: https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=PHP+Fatal+error%3A+Interface+'Guzzle%5CCommon%5CException%5CGuzzleException'+not+found

**Comment by A5hleyRich** [comment]
Are you pulling in a different version of Guzzle or the AWS SDK via composer?

**Comment by ericnicolaas** [comment]
No, this is with the clean version from WordPress. org.

**Comment by polevaultweb** [comment]
@ericnicolaas hey Eric! Does this file exist on your install?

`/path/to/wp/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Common/Exception/GuzzleException.php`

**Comment by ericnicolaas** [comment]
@polevaultweb Hi Iain! Yep, that file exists. I re-uploaded the plugin from WordPress.org, and the previous fatal error is gone now, but replaced with a new one: 

````
PHP Fatal error:  Class 'Guzzle\Service\Command\LocationVisitor\Request\AbstractRequestVisitor' not found in /path/to/wordpress/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/LocationVisitor/Request/HeaderVisitor.php on line 13
````

`/path/to/wordpress/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/LocationVisitor/Request/HeaderVisitor.php` does exist, and it's also referenced in the autoloader's mapping.

**Comment by polevaultweb** [comment]
@ericnicolaas does `/amazon-web-services/vendor/aws/Guzzle/Service/Command/LocationVisitor/Request/AbstractRequestVisitor.php` exist?

**Comment by ericnicolaas** [comment]
Yep.

[image: Screenshot 2016-02-16 23.20.00.png]
It's also referenced in aws-autoloader.php so it *should* be getting picked
up by the autoloader.

Is it possible that this is a BackupBuddy conflict? Just asking because I
see that BB loads version 2.8.10 of the same aws library. I'll test out
whether the problem goes away after deactivating BackupBuddy in the
morning; need to get to bed now. :)

Cheers,
Eric

On Tue, Feb 16, 2016 at 10:56 PM Iain Poulson <notifications@github.com>
wrote:

> @ericnicolaas <https://github.com/ericnicolaas> does
> /amazon-web-services/vendor/aws/Guzzle/Service/Command/LocationVisitor/Request/AbstractRequestVisitor.php
> exist?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deliciousbrains/wp-amazon-web-services/issues/70#issuecomment-184682103>
> .
>
-- 


*Eric Daams*Co-creator of Charitable

wpcharitable.com
twitter.com/wpcharitable

The fundraising alternative for non-profits.
Powered by WordPress.

**Comment by polevaultweb** [comment]
Yep, more than likely the BackupBuddy autoloader files is loaded first.

**Comment by ericnicolaas** [comment]
OK, as expected, deactivating BackupBuddy clears the issue up. I'll get in touch with their support and see if there's a way to bring the AWS SDK in line with the one in Amazon Web Services.

**Comment by polevaultweb** [comment]
@ericnicolaas :+1:

**Comment by ericnicolaas** [comment]
@polevaultweb @A5hleyRich 

I gave up on this for a while, but thought I would have a second attempt at figuring this one out. A few observations:

- Deactivating BackupBuddy makes the issue go away.
- Enabling BackupBuddy but commenting out its autoloader does _not_ prevent the issue. 
- Copying across the same AWS SDK version from Amazon Web Services into BackupBuddy does not prevent the issue either.

This is the error I am getting: 

`[15-Apr-2016 13:14:03 UTC] PHP Fatal error:  Class 'Guzzle\Plugin\Backoff\AbstractErrorCodeBackoffStrategy' not found in /path/to/wordpress/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Plugin/Backoff/HttpBackoffStrategy.php on line 14`

The fact that commenting out the autoloader didn't fix the issue suggests that the autoloader might not be the culprit. But still, deactivating BB removes the issue so _something_ about BB is breaking this. 

Have you heard from anyone else who has encountered conflicts with BackupBuddy?

Cheers, 
Eric

**Comment by aaemnnosttv** [comment]
This is a clear case of a conflict with another plugin using the same SDK or at least some of the dependencies within. If you're only using the AWS plugin for WP Offload S3, then this will be solved in the not too distant future as described [here](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/267#issuecomment-331832031).
