### ISSUE TITLE
Plugin overrides other plugins

### ISSUE THREAD

**Issue by hellomrdavis** [deliciousbrains/wp-amazon-web-services#74]
Hello,

Because I need AWS V3 for a plugin I'm building, I have it in place within my plugin. However, other parts of our site rely on V2 especially WP Offload so we have this plugin activated. The version of AWS you are using is overriding my plugin. If I deactivate this plugin mine works perfectly. If activated, my plugin crashes and throws errors. Any ideas how to remedy this?

Thanks!

**Comment by ianmjones** [comment]
Unfortunately, as wp-amazon-web-services uses the official AWS PHP SDK under the hood, and needs to use v2 as many WordPress sites still use versions of PHP before 5.5, it is incompatible with AWS PHP SDK v3.

We wish we could move to v3 of the AWS PHP SDK, but it's not practical at the moment.

**Comment by hellomrdavis** [comment]
Makes sense.  Is there at least a way to make it so it doesn't override other plug-ins  that are using version three?

**Comment by ianmjones** [comment]
Unfortunately, no, as some class paths/namespaces are the same in the two versions of the AWS PHP SDK.
