### ISSUE TITLE
Using wp-amazon-web-services

### ISSUE THREAD

**Issue by Pulkitmangla** [deliciousbrains/wp-amazon-web-services#75]
Can someone please tell me how to integrate wp-amazon-web-services in my custom made plugin?

**Comment by polevaultweb** [comment]
@Pulkitmangla it depends on what you want your plugin to do? 

We use the plugin with Offload S3 where we extend the AWS base class https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php and use the AWS client to generate an S3 client https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L2426. That might be a good starting point for you.

**Comment by Pulkitmangla** [comment]
I just wanted to know how do I call a function that will execute when the user uploads the file. 
Can you just help me with action or filter should I use to call my function as soon as the files get uploaded?

**Comment by polevaultweb** [comment]
@Pulkitmangla are you using Offload S3? We have a plugin that shows all the hooks available https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php, a number of those run on file upload to S3.

We can't offer support for custom development further than that, I'm afraid.

**Comment by Pulkitmangla** [comment]
@polevaultweb Actually I am just learning to make a plugin which saves the file on the Amazon Server as soon as the user uploads an image. I am stuck on the part where my function is called as soon as the image is uploaded.

**Comment by polevaultweb** [comment]
@Pulkitmangla ah ok, take a look further at our plugin if you wish. Good luck!
