### ISSUE TITLE
Not compatible with "AWS S3 Bucket Browser" plugin

### ISSUE THREAD

**Issue by keithpickering** [deliciousbrains/wp-amazon-web-services#76]
I need to use both of these plugins on a WP multisite; however, when they're both active, WP Offload S3 Lite (which uses this AWS plugin) returns a region error and won't list any of my buckets.

This is probably more the other developer's problem than it is yours, but I can't get them to respond, I don't think that plugin is actively being developed anymore. I think this is a conflict issue with the AWS SDK. If you had any ideas they'd be much appreciated.

**Comment by ianmjones** [comment]
We have plans to namespace and bundle what is needed of the AWS PHP SDK in WP Offload S3 Lite, which will get round any problems with conflicting with other plugins that need a different version of the AWS SDK.

However, that's not going to happen tomorrow, but it is on our relatively short term roadmap.

**Comment by keithpickering** [comment]
Thanks - do you know where I could start looking in the code of the other plugin to change the AWS SDK version? Maybe use the same version included with the AWS plugin if possible?

**Comment by ianmjones** [comment]
Sorry @keithpickering, not familiar with that plugin.

**Comment by aaemnnosttv** [comment]
Sorry @keithpickering. As Ian said, in a future release, WP Offload S3 will no longer require this plugin and you should have no issue, but until then I'm afraid there isn't anything we can do about it.
