### ISSUE TITLE
have you add endpoint in settings

### ISSUE THREAD

**Issue by dxpsite** [deliciousbrains/wp-amazon-web-services#78]
I need it important parameter! or say please where i can change ? Thanks!

**Comment by ianmjones** [comment]
When you use `\Amazon_Web_Services::get_client` the `aws_get_client_args` filter is fired with an array of the [parameters](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html#client-configuration-options), you can add/change the 'endpoint' there.

**Comment by dxpsite** [comment]
sry, i use hotbox service where support s3 protocol -
https://mcs.mail.ru/hotbox/
and for good job need endpoint parameter "hb.bizmrg.com"

2018-01-24 17:48 GMT+03:00 Ian M. Jones <notifications@github.com>:
