### ISSUE TITLE
Where in plugin i can put or change endpoint parameter

### ISSUE THREAD

**Issue by dxpsite** [deliciousbrains/wp-amazon-web-services#79]
sry, i use hotbox service where support s3 protocol - https://mcs.mail.ru/hotbox/ and for good job need endpoint parameter "hb.bizmrg.com"

**Comment by ianmjones** [comment]
Hey @dxpsite I answered this question in https://github.com/deliciousbrains/wp-amazon-web-services/issues/78#issuecomment-360158376

If my previous answer didn't help, please can you re-phrase the question?

**Comment by dxpsite** [comment]
That's right, I would like you to show - in which file of your plug-in you can specify the endpoint parameter

**Comment by ianmjones** [comment]
You can't specify the endpoint in the Amazon Web Services plugin itself, you **must** use the `aws_get_client_args` filter to add in your endpoint. Something like...

```
function my_aws_get_clients_args( $args ) {
    $args['endpoint'] = 'https://hb.bizmrg.com';

    return $args;
}

add_filter( 'aws_get_clients_args', 'my_aws_get_clients_args', 10, 1 );
```

If that does not make sense @dxpsite then I'm afraid the Amazon Web Services plugin probably isn't what you're looking for, it is built to help WordPress plugin developers use the AWS PHP SDK v2 more easily than including it into their plugins directly.

**Comment by dxpsite** [comment]
thanks, i try it and say

**Comment by dxpsite** [comment]
\amazon-web-services\vendor\aws\Aws\Common\Resources\public-endpoints.php
here i change all URLs with "hb.bizmrg.com"
That's work fine!
Big great thanks for help!

**Comment by ianmjones** [comment]
@dxpsite Don't do that! As soon as the plugin is updated you'll loose all your changes and will have to re-do them. Save yourself some pain in the future, use the filter I suggested to override the endpoint used to set up the client connection.

**Comment by dxpsite** [comment]
Thanks again)
